#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 20
bspc config top_padding 20
bspc config split_ratio 0.50

bspc config active_border_color '#96222c'
bspc config focused_border_color '#96222c'
#bspc config normal_border_color '#121212'

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a firefox desktop='^2' follow=on

# Startup
killall -q "sxhkd"; sleep 0.5; sxhkd &
