#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 1
bspc config window_gap 25
bspc config top_padding 22

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config active_border_color "#96222c"
bspc config focused_border_color "#96222c"
#bspc config normal_border_color "#121212"

bspc rule -a Gimp follow=on state=floating

# Startup
killall -q "sxhkd"; sleep 0.5; sxhkd &
