#!/usr/bin/env bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config active_border_color
# bspc config normal_border_color
# bspc config focused_border_color

bspc config top_padding 26

# Startup
killall -q "sxhkd"; sleep 0.5; sxhkd &
