hl.on("hyprland.start", function ()
  hl.exec_cmd("~/.config/sway/lock.sh & ~/.config/sway/idle.sh")
  hl.exec_cmd("wl-paste -p -t text --watch clipman store -P --histpath='~/.local/share/clipman-primary.json'")
  hl.exec_cmd("dunst")
  hl.exec_cmd("udiskie")
  hl.exec_cmd("waybar & hyprpaper & firefox")
end)
